version: '3'
services:
  db:
    image: postgres:12
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'DATABASE_NAME=postgres'

    healthcheck:
      test: pg_isready -d postgres -U postgres
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  web:
    build: .
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'DATABASE_NAME=postgres'
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
